# Generated by Django 4.1.4 on 2022-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('adress_title', models.CharField(max_length=255)),
                ('adress_text', models.CharField(max_length=255)),
                ('tel', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('email', models.CharField(max_length=255)),
                ('facebooke', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('linked', models.CharField(max_length=255)),
            ],
        ),
    ]
