# Generated by Django 4.1.4 on 2022-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_logo_logo_logo1_logo_logo10_logo_logo2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('title4', models.CharField(max_length=255)),
                ('text4', models.CharField(max_length=255)),
            ],
        ),
    ]
