# Generated by Django 4.1.4 on 2022-12-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_text',
            name='text2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
