# Generated by Django 4.1.4 on 2022-12-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_project_texts1_project_texts2_project_texts3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rigth', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('advantege', models.ManyToManyField(to='main.advantege')),
            ],
        ),
    ]
