# Generated by Django 4.1.4 on 2022-12-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_advantege_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='youtube',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
