# Generated by Django 4.1.4 on 2022-12-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_about_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='advantege',
        ),
        migrations.DeleteModel(
            name='Advantege',
        ),
    ]
