# Generated by Django 4.1.4 on 2022-12-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_frequently_frequently_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequently',
            old_name='text',
            new_name='ansver1',
        ),
        migrations.RenameField(
            model_name='frequently',
            old_name='title',
            new_name='ansver2',
        ),
        migrations.AddField(
            model_name='frequently',
            name='ansver3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequently',
            name='ansver4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequently',
            name='question1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequently',
            name='question2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequently',
            name='question3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequently',
            name='question4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
