# Generated by Django 4.1.4 on 2022-12-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_text_frequently_ansver1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequently',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
