# Generated by Django 4.1.4 on 2022-12-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_frequently_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequently',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
