# Generated by Django 4.1.4 on 2022-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_frequently_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='download',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='first_title1',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='first_title2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='rigth',
        ),
        migrations.RemoveField(
            model_name='about',
            name='youtube',
        ),
        migrations.AddField(
            model_name='about',
            name='img2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='text1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
