# Generated by Django 4.1.4 on 2022-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_name_about_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
    ]
