# Generated by Django 4.1.4 on 2022-12-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_about_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impor_title', models.CharField(max_length=255)),
                ('impor_text', models.TextField(max_length=255)),
                ('impor_text2', models.CharField(max_length=255)),
                ('img1', models.ImageField(upload_to='')),
                ('img2', models.ImageField(upload_to='')),
                ('img3', models.ImageField(upload_to='')),
                ('img4', models.ImageField(upload_to='')),
                ('title1', models.CharField(max_length=255)),
                ('text1', models.TextField()),
                ('name1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('text2', models.TextField()),
                ('name2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('text3', models.TextField()),
                ('name3', models.CharField(max_length=255)),
                ('title4', models.CharField(max_length=255)),
                ('text4', models.TextField()),
                ('name4', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='youtube',
        ),
    ]
