# Generated by Django 4.1.4 on 2022-12-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_communyte_remove_about_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communyte',
            old_name='img1',
            new_name='imgs1',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='img2',
            new_name='imgs2',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='img3',
            new_name='imgs3',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='img4',
            new_name='imgs4',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='impor_title',
            new_name='impor_text3',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='name1',
            new_name='impor_title2',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='name2',
            new_name='names1',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='name3',
            new_name='names2',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='name4',
            new_name='names3',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='title1',
            new_name='names4',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='text1',
            new_name='texts1',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='text2',
            new_name='texts2',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='text3',
            new_name='texts3',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='text4',
            new_name='texts4',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='title2',
            new_name='titles1',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='title3',
            new_name='titles2',
        ),
        migrations.RenameField(
            model_name='communyte',
            old_name='title4',
            new_name='titles3',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='impor_text',
        ),
        migrations.AddField(
            model_name='communyte',
            name='titles4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communyte',
            name='impor_text2',
            field=models.TextField(max_length=255),
        ),
    ]
