# Generated by Django 4.1.4 on 2022-12-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_img1_communyte_imgs1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
