# Generated by Django 4.1.4 on 2022-12-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_conversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequently',
            old_name='ansver1',
            new_name='ansver',
        ),
        migrations.RenameField(
            model_name='frequently',
            old_name='ansver2',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='frequently',
            name='ansver3',
        ),
        migrations.RemoveField(
            model_name='frequently',
            name='ansver4',
        ),
        migrations.RemoveField(
            model_name='frequently',
            name='img',
        ),
        migrations.RemoveField(
            model_name='frequently',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='frequently',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='frequently',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='frequently',
            name='question4',
        ),
    ]
