# Generated by Django 4.1.4 on 2022-12-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_ansver1_frequently_ansver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communyte',
            name='imgs2',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='imgs3',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='imgs4',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='impor_text2',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='impor_text3',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='impor_title2',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='names2',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='names3',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='names4',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='texts2',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='texts3',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='texts4',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='titles2',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='titles3',
        ),
        migrations.RemoveField(
            model_name='communyte',
            name='titles4',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='impor_text',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='impor_title',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='numers2',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='numers3',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='numers4',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='suppor',
            name='title4',
        ),
    ]
